version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - 15672:15672
    networks:
      - bookstore
  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2113:2113
    volumes:
      - type: bind
        source: c:/EventStoreData
        target: /var/lib/eventstore
      - eventstore-volume-logs:/var/log/eventstore
    networks:
      - bookstore
  bookstore.service.subject:
    image: ${DOCKER_REGISTRY-}bookstoreservicesubject
    build:
      context: .
      dockerfile: Service/Bookstore.Service.Subject/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    restart: always
    depends_on:
      - eventstore
      - rabbitmq
    networks:
      - bookstore
  bookstore.ui.web.server:
    labels:
      - traefik.http.routers.bookstore.rule=Host(`bookstore.local`)
      - traefik.http.routers.bookstore.tls=true
      - traefik.http.routers.bookstore.entrypoints=websecure
    image: ${DOCKER_REGISTRY-}bookstoreuiwebserver
    build:
      context: .
      dockerfile: UI/Web/Bookstore/Server/Dockerfile
    volumes:
      - "${USERPROFILE-C:/Users/Default}/.aspnet/https:/https:ro"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - traefik_default
      - bookstore
    restart: always
    depends_on:
      - bookstore.service.subject
      - rabbitmq

volumes:
  eventstore-volume-logs:

networks:
  traefik_default:
    external: true
  bookstore:
    external: true